### ISSUE TITLE
[Text] Introduce AttributedText Class

### ISSUE THREAD

**Issue by Ali-Alzyoud** [dalihub/dali-toolkit#13]
Add public API to deal with AttributedText Class, which allows the user to set/get/modify the rich text(plain text + formats) in text controllers.
This is similar to what other platforms have:

https://developer.apple.com/documentation/foundation/nsattributedstring 
https://developer.android.com/guide/topics/text/spans

For Phase 1: we will support immutable Class only.

Additional:
Supporting HTML/CSS can be done, by extending AttributedText Class to save/load from HTML content. (#6)

**Comment by adeelkazmi** [comment]
The span functionality has recently been added so closing this.
