### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by JakeSays** [dalihub/dali-toolkit#14]
When building I get this:

> [  0%] Building CXX object CMakeFiles/dali-toolkit.dir/p/misc/tizen/nui/dali-toolkit/dali-toolkit/internal/builder/builder-animations.cpp.o
In file included from /p/misc/tizen/nui/dali-toolkit/dali-toolkit/internal/builder/builder-animations.cpp:23:
/p/misc/tizen/nui/dali-toolkit/dali-toolkit/internal/builder/builder-impl.h:25:10: fatal error: dali/public-api/common/stage.h: No such file or directory
   25 | #include <dali/public-api/common/stage.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/dali-toolkit.dir/build.make:76: CMakeFiles/dali-toolkit.dir/p/misc/tizen/nui/dali-toolkit/dali-toolkit/internal/builder/builder-animations.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:117: CMakeFiles/dali-toolkit.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

I am building on ubuntu 20.04. I have successfully built dali-core and the missing header is in the `dali-env` location where core was installed, and `$DESKTOP_PREFIX=/p/misc/tizen/nui/dali-env/opt`. Am I missing a step? Also is there a particular order in which the various repos should be built?

**Comment by adeelkazmi** [comment]
Hi @JakeSays, sorry, only just noticed this issue. I think there may have been a mismatch when you tried to build this. This should no longer be the case with the very latest code now.

**Comment by JakeSays** [comment]
@adeelkazmi ah well I forgot I filed it:) I was doing an experiment and had to move on to other things, but I'm still interested in nui running on ubuntu so I'll give it another try.

**Comment by adeelkazmi** [comment]
OK, cool, let me know if you have any issues compiling - I'll try and respond quicker next time :)

**Comment by JakeSays** [comment]
Not getting this issue with latest code on master.
