### ISSUE TITLE
[Text] Atals Size For Glyphs

### ISSUE THREAD

**Issue by Ali-Alzyoud** [dalihub/dali-toolkit#5]
It seems Dali will always request the Same Atlas size, for all font instance glyphs regardless of glyph real size.
So maybe there is room for memory enhancement when caching glyph bitmaps

**Comment by Ali-Alzyoud** [comment]
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/255164
Add Support for larger Atlas size

**Comment by adeelkazmi** [comment]
Looks like this patch has been merged so closing this issue.
